version: 2.0

jobs:
  build:

    docker:
    - image: circleci/openjdk:8-jdk

    working_directory: ~/walking-skeleton

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
            key: gradle-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test