version: 2.0

jobs:
  build:

    working_directory: ~/walking-skeleton

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}

      - run: gradle assemble
      - run: gradle run
      - run: gradle test

      - save_cache:
          paths:
            - ~/.gradle
            key: gradle-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/distributions
          destination: distributions

      - store_artifacts:
          path: build/libs
          destination: libs